name: drawiloo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  html: ^0.15.5
  http: ^1.3.0
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/circle.png
    - assets/image/bomba.png
    - assets/image/cle.png
    - assets/image/triangle.png
    - assets/image/play.png
    - assets/image/cup.png
    - assets/image/1.png
    - assets/image/2.png
    - assets/image/3.png
    - assets/image/logo.png
    - assets/image/log.png
    - assets/image/splash.png
